version: '2'
services:
  api-tree:
    image: blueforest/api-tree:latest
    environment:
      DB_HOST: trees-mongo
      DB_USER:
      DB_PWD:
      NODE_ENV: production
      PORT: '8080'
    stdin_open: true
    volumes:
    - /etc/api-tree:/etc/api-tree:ro
    tty: true
    links:
    - trees-mongo:database
    labels:
      io.rancher.container.pull_image: always
  trees-mongo:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    stdin_open: true
    volumes:
    - /var/lib/trees/mongo:/data/db
    command: mongod --auth
    tty: true
    labels:
      io.rancher.container.pull_image: always
    ports:
    - 27277:27017
  web:
    image: nginx:latest
    stdin_open: true
    volumes:
    - /etc/nginx/blueforest.org:/etc/nginx:ro
    - /var/www/blueforest.org:/var/www:ro
    tty: true
    links:
    - api-tree:api-tree
    labels:
      io.rancher.container.pull_image: always