version: '2'
services:
  user:
    image: blueforest/user:1.0.5
    environment:
      DB_HOST: mongo
      DB_USER: XXX
      DB_PWD: YYY
      NODE_ENV: production
      PORT: '8080'
      DEBUG: api:*
      AUTH_TOKEN_SECRET: ZZZ
    links:
    - mongo:database
    volumes:
      - /etc/user:/etc/user
  message:
    image: blueforest/message:latest
    environment:
      DB_HOST: mongo
      DB_USER: XXX
      DB_PWD: YYY
      NODE_ENV: production
      PORT: '8080'
      DEBUG: api:*
    links:
    - mongo:database
  film:
    image: blueforest/film:1.0.4
    environment:
      DB_HOST: mongo
      DB_USER: XXX
      DB_PWD: YYY
      NODE_ENV: production
      PORT: '8080'
      DEBUG: api:*
    links:
    - mongo:database
  facet:
    image: blueforest/attribute:1.0.2
    environment:
      NAME: facet
      DB_HOST: mongo
      DB_USER: XXX
      DB_PWD: YYY
      NODE_ENV: production
      DEBUG: api:*
      TREE_BASE_URL: "http://trees"
    links:
    - mongo:database
    - trees:trees
  damage:
    image: blueforest/attribute:1.0.2
    environment:
      NAME: damage
      DB_HOST: mongo
      DB_USER: XXX
      DB_PWD: YYY
      NODE_ENV: production
      DEBUG: api:*
      TREE_BASE_URL: "http://trees"
    links:
    - mongo:database
    - trees:trees
  impact:
    image: blueforest/attribute:1.0.2
    environment:
      NAME: impact
      DB_HOST: mongo
      DB_USER: XXX
      DB_PWD: YYY
      NODE_ENV: production
      DEBUG: api:*
      TREE_BASE_URL: "http://trees"
    links:
    - mongo:database
    - trees:trees
  categorie:
    image: blueforest/categorie:latest
    environment:
      DB_HOST: mongo
      DB_USER: XXX
      DB_PWD: YYY
      NODE_ENV: production
      PORT: '8080'
      DEBUG: api:*
    links:
    - mongo:database
  grandeur:
    image: blueforest/grandeur:latest
    environment:
      NODE_ENV: production
      PORT: '8080'
      DEBUG: api:*
  import:
    image: blueforest/import:1.0.12
    environment:
      DB_HOST: mongo
      DB_USER: XXX
      DB_PWD: YYY
      NODE_ENV: production
      DEBUG: api:*
      USER_BASE_URL: "http://user:8080"
    links:
    - mongo:database
    - user:user
  trees:
    image: blueforest/trees:1.0.5
    environment:
      DB_HOST: mongo
      DB_USER: XXX
      DB_PWD: YYY
      NODE_ENV: production
      DEBUG: api:*
    links:
    - mongo:database
  mongo:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: XXX
      MONGO_INITDB_ROOT_PASSWORD: YYY
    volumes:
    - /var/lib/trees/mongo:/data/db
    command: mongod --auth
    ports:
    - 27277:27017
  api:
    image: openresty/openresty:alpine
    volumes:
    - /etc/nginx/blueforest.org/api/:/usr/local/openresty/nginx/conf/:ro
    environment:
      JWT_SECRET: ZZZ
    links:
    - trees:trees
    - user:user
    - categorie:categorie
    - damage:damage
    - impact:impact
    - grandeur:grandeur
    - import:import
  web:
    image: nginx:latest
    volumes:
    - /etc/nginx/blueforest.org/web:/etc/nginx:ro
    - /var/www/blueforest.org:/var/www:ro
  draw:
    image: nginx:latest
    volumes:
    - /etc/nginx/draw.blueforest.org/web:/etc/nginx:ro
    - /var/www/draw.blueforest.org:/var/www:ro