version: "2"

services:
  nginx:
    image: pixelfordinner/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/www/frontal/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "/var/www/frontal/nginx/vhost.d:/etc/nginx/vhost.d:ro"
      - "/var/www/frontal/static/certs:/etc/nginx/certs:ro"
      - "/usr/share/nginx/html"
    networks:
      - proxy-tier
    labels:
        io.rancher.sidekicks: lets-encrypt-companion,docker-gen
  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    restart: unless-stopped
    depends_on:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/var/www/frontal/docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "/var/www/frontal/nginx/conf.d:/etc/nginx/conf.d:rw"
    networks:
      - proxy-tier
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  lets-encrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.6
    container_name: letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx
      - docker-gen
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/www/frontal/nginx/vhost.d:/etc/nginx/vhost.d:rw"
      - "/var/www/frontal/static/certs:/etc/nginx/certs:rw"
    environment:
      - "NGINX_DOCKER_GEN_CONTAINER=docker-gen"
     # - "ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory"
     # - "DEBUG=true"

networks:
  proxy-tier:
    external:
      name: "nginx-proxy"